In [1]:
import keras
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense, Conv2D, MaxPool2D, Flatten, Dropout
import matplotlib.pyplot as plt
from keras.callbacks import EarlyStopping, TensorBoard

Using TensorFlow backend.


In [2]:
batch_size = 100
epochs = 10

In [3]:
(X_Train,y_Train),(X_Test,y_Test) = mnist.load_data()

11493376/11490434 [==============================] - 29s 3us/step


In [6]:
print(X_Train)

[[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 ...

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]]


In [7]:
X_Train = X_Train.reshape(X_Train.shape[0],X_Train.shape[1],X_Train.shape[2],1)
X_Test = X_Test.reshape(X_Test.shape[0],X_Test.shape[1],X_Test.shape[2],1)

In [8]:
print(X_Train)

[[[[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]

  ...

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]]


 [[[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]

  ...

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]]


 [[[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]

  ...

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]]


 ...


 [[[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]

In [9]:
y_Train = keras.utils.to_categorical(y_Train, 10)
y_Test = keras.utils.to_categorical(y_Test, 10)

In [10]:
# Creating Model
model = Sequential()

model.add(Conv2D(100, kernel_size=3, activation='relu',input_shape=(28,28,1)))
model.add(MaxPool2D(pool_size=(3,3)))

model.add(Dropout(0.25))

model.add(Conv2D(150, kernel_size=2, activation='relu'))
model.add(MaxPool2D(pool_size=(2,2)))

model.add(Conv2D(50, kernel_size=2, activation='relu'))
model.add(MaxPool2D(pool_size=(2,2)))

model.add(Dropout(0.2))

model.add(Flatten())

model.add(Dense(10,activation='softmax'))

In [11]:
callback_list = [EarlyStopping(patience=2)]

In [12]:
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [13]:
model.fit(X_Train,y_Train,batch_size=100,epochs=20,validation_split=0.2,callbacks=callback_list)

Train on 48000 samples, validate on 12000 samples
Epoch 1/20
48000/48000 [==============================] - 63s 1ms/step - loss: 1.7489 - accuracy: 0.5334 - val_loss: 0.3142 - val_accuracy: 0.9090
Epoch 2/20
48000/48000 [==============================] - 60s 1ms/step - loss: 0.4905 - accuracy: 0.8428 - val_loss: 0.1511 - val_accuracy: 0.9548
Epoch 3/20
48000/48000 [==============================] - 66s 1ms/step - loss: 0.3057 - accuracy: 0.9039 - val_loss: 0.1154 - val_accuracy: 0.9663
Epoch 4/20
48000/48000 [==============================] - 61s 1ms/step - loss: 0.2312 - accuracy: 0.9289 - val_loss: 0.1032 - val_accuracy: 0.9693
Epoch 5/20
48000/48000 [==============================] - 60s 1ms/step - loss: 0.1881 - accuracy: 0.9430 - val_loss: 0.1016 - val_accuracy: 0.9715
Epoch 6/20
48000/48000 [==============================] - 60s 1ms/step - loss: 0.1657 - accuracy: 0.9494 - val_loss: 0.0743 - val_accuracy: 0.9789
Epoch 7/20
48000/48000 [==============================] - 60s 1ms/st

In [14]:
model.evaluate(X_Test,y_Test)

10000/10000 [==============================] - 4s 397us/step


[0.0653415813805419, 0.9818999767303467]